version: '3.1'
services:
  stats-server:
    build: statistics-explore-with-me/stat-service
    image: statistic-ewm
    container_name: StatisticService_ewm
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING.DATASOURCE.USERNAME=root
      - SPRING.DATASOURCE.PASSWORD=root
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    container_name: statisticsDb_ewm
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  ewm-service:
#    build: /main-service-explore-with-me
#    image: main-service-explore-with-me
#    container_name: MainService_ewm
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
#    depends_on:
#      - ewm-db
#      - stats-server
#
#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ServiceDB_ewm
#    ports:
#      - "6541:5432"
#    environment:
#      - POSTGRES_DB=ewm-db
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
